/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface JtStockFinder {}
  interface JtStockFinderAttributes extends StencilHTMLAttributes {
    'onJtSymbolSelected'?: (event: CustomEvent<string>) => void;
  }

  interface JtStockPrices {
    'stockSymbol': string;
  }
  interface JtStockPricesAttributes extends StencilHTMLAttributes {
    'stockSymbol'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'JtStockFinder': Components.JtStockFinder;
    'JtStockPrices': Components.JtStockPrices;
  }

  interface StencilIntrinsicElements {
    'jt-stock-finder': Components.JtStockFinderAttributes;
    'jt-stock-prices': Components.JtStockPricesAttributes;
  }


  interface HTMLJtStockFinderElement extends Components.JtStockFinder, HTMLStencilElement {}
  var HTMLJtStockFinderElement: {
    prototype: HTMLJtStockFinderElement;
    new (): HTMLJtStockFinderElement;
  };

  interface HTMLJtStockPricesElement extends Components.JtStockPrices, HTMLStencilElement {}
  var HTMLJtStockPricesElement: {
    prototype: HTMLJtStockPricesElement;
    new (): HTMLJtStockPricesElement;
  };

  interface HTMLElementTagNameMap {
    'jt-stock-finder': HTMLJtStockFinderElement
    'jt-stock-prices': HTMLJtStockPricesElement
  }

  interface ElementTagNameMap {
    'jt-stock-finder': HTMLJtStockFinderElement;
    'jt-stock-prices': HTMLJtStockPricesElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
