/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface JtStockPrices {}
  interface JtStockPricesAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'JtStockPrices': Components.JtStockPrices;
  }

  interface StencilIntrinsicElements {
    'jt-stock-prices': Components.JtStockPricesAttributes;
  }


  interface HTMLJtStockPricesElement extends Components.JtStockPrices, HTMLStencilElement {}
  var HTMLJtStockPricesElement: {
    prototype: HTMLJtStockPricesElement;
    new (): HTMLJtStockPricesElement;
  };

  interface HTMLElementTagNameMap {
    'jt-stock-prices': HTMLJtStockPricesElement
  }

  interface ElementTagNameMap {
    'jt-stock-prices': HTMLJtStockPricesElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
